<?php
session_start();
$configPath = __DIR__ . '/config.php';
if (!file_exists($configPath)) $configPath = __DIR__ . '/config.example.php';
$config = require $configPath;
date_default_timezone_set($config['timezone'] ?? 'Asia/Tehran');

function h($v){ return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
function post($k,$d=null){ return $_POST[$k] ?? $d; }
function db(){ static $pdo; global $config; if(!$pdo){ $d=$config['db']; $pdo=new PDO("mysql:host={$d['host']};dbname={$d['name']};charset={$d['charset']}",$d['user'],$d['pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]); } return $pdo; }
function q($sql,$p=[]){ $s=db()->prepare($sql); $s->execute($p); return $s; }
function all($sql,$p=[]){ return q($sql,$p)->fetchAll(); }
function one($sql,$p=[]){ return q($sql,$p)->fetch(); }
function go($v='dashboard'){ header('Location: ?view='.$v); exit; }
function ok(){ return !empty($_SESSION['ok']); }
function pass_ok($email,$password){ global $config; $a=$config['admin']; if(!hash_equals($a['email'],trim($email))) return false; if(str_starts_with($a['password_hash'],'CHANGE_')) return false; $hash=hash_pbkdf2('sha256',$password,$a['password_salt'],(int)$a['password_iterations'],64); return hash_equals($a['password_hash'],$hash); }
function ai($prompt){ global $config; $key=trim($config['openai']['api_key'] ?? ''); if($key==='') return 'OpenAI API Key هنوز در config.php تنظیم نشده است.'; $payload=json_encode(['model'=>$config['openai']['model'] ?: 'gpt-5-mini','input'=>[['role'=>'system','content'=>'تو دستیار فارسی یک داوطلب کنکور کارشناسی ارشد زیست و بیوتکنولوژی هستی. پاسخ‌ها دقیق، آموزشی و کوتاه باشند.'],['role'=>'user','content'=>$prompt]]],JSON_UNESCAPED_UNICODE); $ch=curl_init('https://api.openai.com/v1/responses'); curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$key,'Content-Type: application/json'],CURLOPT_POSTFIELDS=>$payload,CURLOPT_TIMEOUT=>45]); $raw=curl_exec($ch); if($raw===false) return 'خطا در اتصال: '.curl_error($ch); $data=json_decode($raw,true); if(!empty($data['error']['message'])) return 'خطای OpenAI: '.$data['error']['message']; if(!empty($data['output_text'])) return $data['output_text']; $out=[]; foreach(($data['output']??[]) as $item) foreach(($item['content']??[]) as $c) if(!empty($c['text'])) $out[]=$c['text']; return $out ? implode("\n",$out) : 'پاسخی دریافت نشد.'; }
function opts($items,$sel=null){ $html='<option value="">انتخاب نشده</option>'; foreach($items as $i){ $s=((string)$sel===(string)$i['id'])?' selected':''; $html.='<option value="'.h($i['id']).'"'.$s.'>'.h($i['title']).'</option>'; } return $html; }
function review_topic($topic,$date=null){ $date=$date ?: date('Y-m-d'); foreach([1,3,7,14,30] as $d) q('INSERT INTO reviews(item_type,item_id,due_on) VALUES(?,?,?)',['topic',$topic,date('Y-m-d',strtotime($date." +$d days"))]); }
function days_left(){ global $config; return (new DateTime(date('Y-m-d')))->diff(new DateTime($config['exam_date']))->format('%r%a'); }

if($_SERVER['REQUEST_METHOD']==='POST'){
  $a=post('action');
  try{
    if($a==='login'){ if(pass_ok(post('email'),post('password'))){ $_SESSION['ok']=1; go(); } $_SESSION['flash']='ایمیل یا رمز درست نیست، یا password_hash هنوز تنظیم نشده است.'; go('login'); }
    if($a==='logout'){ session_destroy(); go('login'); }
    if(!ok()) go('login');
    if($a==='study'){ q('INSERT INTO study_sessions(subject_id,topic_id,studied_on,minutes,activity,focus_score,notes) VALUES(?,?,?,?,?,?,?)',[post('subject_id'),post('topic_id')?:null,post('studied_on'),post('minutes'),post('activity'),post('focus_score'),post('notes')]); if(post('topic_id')){ q('UPDATE topics SET mastery=LEAST(100,mastery+?) WHERE id=?',[post('activity')==='test'?4:3,post('topic_id')]); review_topic(post('topic_id'),post('studied_on')); } go('study'); }
    if($a==='plan'){ q('INSERT INTO plans(due_on,scope,subject_id,topic_id,title,target_minutes) VALUES(?,?,?,?,?,?)',[post('due_on'),post('scope'),post('subject_id')?:null,post('topic_id')?:null,post('title'),post('target_minutes')?:0]); go('plan'); }
    if($a==='done_plan'){ q("UPDATE plans SET status='done' WHERE id=?",[post('id')]); go('plan'); }
    if($a==='review'){ q("UPDATE reviews SET status='done',recall_score=? WHERE id=?",[post('recall_score'),post('id')]); if(post('item_type')==='topic') q('UPDATE topics SET mastery=GREATEST(0,LEAST(100,mastery+?)) WHERE id=?',[(int)post('recall_score')>=4?4:-3,post('item_id')]); go('reviews'); }
    if($a==='question'){ q('INSERT INTO questions(subject_id,topic_id,body,option_a,option_b,option_c,option_d,correct_option,explanation,source,difficulty,kind,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',[post('subject_id')?:null,post('topic_id')?:null,post('body'),post('option_a'),post('option_b'),post('option_c'),post('option_d'),post('correct_option'),post('explanation'),post('source'),post('difficulty'),post('kind'),'approved']); go('questions'); }
    if($a==='import_questions'){ foreach(preg_split("/\n\s*\n/u",trim(post('bulk_text'))) as $b) if(trim($b)!=='') q('INSERT INTO questions(body,source,status) VALUES(?,?,?)',[trim($b),post('source')?:'ورود متنی','review']); go('questions'); }
    if($a==='error'){ q('INSERT INTO error_logs(subject_id,topic_id,title,body,error_type,status,occurred_on) VALUES(?,?,?,?,?,?,?)',[post('subject_id')?:null,post('topic_id')?:null,post('title'),post('body'),post('error_type'),post('status'),post('occurred_on')]); q('INSERT INTO reviews(item_type,item_id,due_on) VALUES(?,?,?)',['error',db()->lastInsertId(),date('Y-m-d',strtotime('+2 days'))]); go('errors'); }
    if($a==='flashcard'){ q('INSERT INTO flashcards(subject_id,topic_id,front,back,difficulty,next_review_on,created_by) VALUES(?,?,?,?,?,?,?)',[post('subject_id')?:null,post('topic_id')?:null,post('front'),post('back'),post('difficulty'),post('next_review_on')?:date('Y-m-d',strtotime('+1 day')),'manual']); q('INSERT INTO reviews(item_type,item_id,due_on) VALUES(?,?,?)',['flashcard',db()->lastInsertId(),post('next_review_on')?:date('Y-m-d',strtotime('+1 day'))]); go('flashcards'); }
    if($a==='ai_flashcards'){ $_SESSION['ai_result']=ai('از متن زیر ۵ فلش‌کارت فارسی برای کنکور ارشد زیست/بیوتکنولوژی بساز. قالب: سوال: ... پاسخ: ... متن: '.post('source_text')); go('flashcards'); }
    if($a==='checkin'){ q('REPLACE INTO daily_checkins(checked_on,energy,focus,sleep_hours,stress,note) VALUES(?,?,?,?,?,?)',[post('checked_on'),post('energy'),post('focus'),post('sleep_hours'),post('stress'),post('note')]); go(); }
    if($a==='pomodoro'){ q('INSERT INTO pomodoro_sessions(subject_id,topic_id,minutes,status) VALUES(?,?,?,?)',[post('subject_id')?:null,post('topic_id')?:null,post('minutes'),'completed']); q('INSERT INTO study_sessions(subject_id,topic_id,studied_on,minutes,activity,focus_score,notes) VALUES(?,?,?,?,?,?,?)',[post('subject_id'),post('topic_id')?:null,date('Y-m-d'),post('minutes'),'study',4,'ثبت‌شده از تایمر پومودورو']); go('pomodoro'); }
    if($a==='chat'){ $tid=post('thread_id'); if(!$tid){ q('INSERT INTO chat_threads(title,subject_id,topic_id) VALUES(?,?,?)',[mb_substr(post('message'),0,80),post('subject_id')?:null,post('topic_id')?:null]); $tid=db()->lastInsertId(); } q('INSERT INTO chat_messages(thread_id,role,body) VALUES(?,?,?)',[$tid,'user',post('message')]); q('INSERT INTO chat_messages(thread_id,role,body) VALUES(?,?,?)',[$tid,'assistant',ai(post('message'))]); go('chat&thread_id='.$tid); }
    if($a==='finish_exam'){ $ids=$_POST['question_ids']??[]; q('INSERT INTO exams(title,topic_id,total_questions) VALUES(?,?,?)',['آزمون مبحثی',post('topic_id')?:null,count($ids)]); $eid=db()->lastInsertId(); $correct=0; foreach($ids as $id){ $qu=one('SELECT * FROM questions WHERE id=?',[$id]); $sel=$_POST['answer'][$id]??null; $ok=$qu && $sel===$qu['correct_option']; if($ok)$correct++; q('INSERT INTO exam_answers(exam_id,question_id,selected_option,is_correct) VALUES(?,?,?,?)',[$eid,$id,$sel,$ok?1:0]); q('UPDATE questions SET times_used=times_used+1, correct_count=correct_count+? WHERE id=?',[$ok?1:0,$id]); if(!$ok && $qu) q('INSERT INTO error_logs(subject_id,topic_id,question_id,title,body,error_type,status,occurred_on) VALUES(?,?,?,?,?,?,?,?)',[$qu['subject_id'],$qu['topic_id'],$id,'اشتباه در آزمون: سوال #'.$id,$qu['body'],'conceptual','new',date('Y-m-d')]); } q('UPDATE exams SET correct_answers=? WHERE id=?',[$correct,$eid]); go('reports'); }
  }catch(Throwable $e){ $_SESSION['flash']='خطا: '.$e->getMessage(); go($_GET['view']??'dashboard'); }
}

$view=$_GET['view']??'dashboard'; if(!ok() && $view!=='login') $view='login';
if($view==='login'){ echo '<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="assets/styles.css"><title>ورود</title></head><body><div class="login"><form method="post" class="card"><h1>ورود به استادا</h1>'; if(!empty($_SESSION['flash'])){ echo '<div class="notice">'.h($_SESSION['flash']).'</div>'; unset($_SESSION['flash']); } echo '<input type="hidden" name="action" value="login"><label>ایمیل<input name="email" type="email" required></label><br><label>رمز عبور<input name="password" type="password" required></label><div class="actions"><button class="btn">ورود</button></div></form></div></body></html>'; exit; }
$subjects=all('SELECT * FROM subjects ORDER BY title'); $topics=all('SELECT topics.*,subjects.title subject_title FROM topics JOIN subjects ON subjects.id=topics.subject_id ORDER BY subjects.title,topics.title');
function st($subjects,$topics){ echo '<label>درس<select name="subject_id">'.opts($subjects).'</select></label><label>مبحث<select name="topic_id">'.opts($topics).'</select></label>'; }
function header_app($view){ global $config; $nav=['dashboard'=>'داشبورد','study'=>'ثبت مطالعه','plan'=>'برنامه','reviews'=>'مرور','pomodoro'=>'پومودورو','questions'=>'بانک سوال','exam'=>'آزمون','errors'=>'دفترچه خطا','flashcards'=>'فلش‌کارت','chat'=>'دستیار AI','reports'=>'گزارش']; echo '<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.h($config['app_name']).'</title><link rel="stylesheet" href="assets/styles.css"></head><body><div class="shell"><aside class="side"><div class="brand">'.h($config['app_name']).'</div><nav class="nav">'; foreach($nav as $k=>$v) echo '<a class="'.($view===$k?'active':'').'" href="?view='.h($k).'">'.h($v).'</a>'; echo '</nav><form method="post" class="actions"><input type="hidden" name="action" value="logout"><button class="btn secondary">خروج</button></form></aside><main class="main">'; if(!empty($_SESSION['flash'])){ echo '<div class="notice">'.h($_SESSION['flash']).'</div>'; unset($_SESSION['flash']); } }
header_app($view);

if($view==='dashboard'){ $today=date('Y-m-d'); $m=one('SELECT COALESCE(SUM(minutes),0) total FROM study_sessions WHERE studied_on=?',[$today])['total']??0; $w=one('SELECT COALESCE(SUM(minutes),0) total FROM study_sessions WHERE studied_on BETWEEN ? AND ?',[date('Y-m-d',strtotime('-6 days')),$today])['total']??0; $due=one("SELECT COUNT(*) c FROM reviews WHERE status='due' AND due_on<=?",[$today])['c']??0; $mas=one('SELECT COALESCE(AVG(mastery),0) m FROM topics')['m']??0; $ready=min(100,round($mas*.45+min(35,$w/60*2)+max(0,20-$due))); $plans=all("SELECT * FROM plans WHERE due_on=? AND status='todo'",[$today]); echo '<div class="topbar"><div class="title"><h1>داشبورد امروز</h1><p>شمارش معکوس، برنامه، مرور و آمادگی.</p></div><span class="badge">'.h($today).'</span></div><section class="grid"><div class="card span-3 metric"><span>روز باقی‌مانده</span><b>'.h(days_left()).'</b></div><div class="card span-3 metric"><span>مطالعه امروز</span><b>'.h(round($m/60,1)).'h</b></div><div class="card span-3 metric"><span>مرورهای باز</span><b>'.h($due).'</b></div><div class="card span-3 metric"><span>آمادگی</span><b>'.h($ready).'%</b><div class="progress"><i style="width:'.h($ready).'%"></i></div></div><div class="card span-6"><h2>برنامه امروز</h2><div class="list">'; foreach($plans as $p) echo '<div class="item"><strong>'.h($p['title']).'</strong><span class="small">'.h($p['target_minutes']).' دقیقه</span></div>'; if(!$plans) echo '<p class="small">برای امروز برنامه‌ای ثبت نشده.</p>'; echo '</div></div><form method="post" class="card span-6"><h2>چک‌این روزانه</h2><input type="hidden" name="action" value="checkin"><div class="form-grid"><label>تاریخ<input type="date" name="checked_on" value="'.h($today).'"></label><label>خواب<input type="number" step=".5" name="sleep_hours" value="7"></label><label>انرژی<input type="number" min="1" max="5" name="energy" value="3"></label><label>تمرکز<input type="number" min="1" max="5" name="focus" value="3"></label><label>استرس<input type="number" min="1" max="5" name="stress" value="3"></label><label>یادداشت<textarea name="note"></textarea></label></div><button class="btn">ثبت</button></form></section>'; }
if($view==='study'){ $rows=all('SELECT study_sessions.*,subjects.title subject_title,topics.title topic_title FROM study_sessions JOIN subjects ON subjects.id=study_sessions.subject_id LEFT JOIN topics ON topics.id=study_sessions.topic_id ORDER BY studied_on DESC,id DESC LIMIT 20'); echo '<div class="title"><h1>ثبت مطالعه</h1></div><section class="grid"><form method="post" class="card span-5"><input type="hidden" name="action" value="study"><div class="form-grid">'; st($subjects,$topics); echo '<label>تاریخ<input type="date" name="studied_on" value="'.date('Y-m-d').'"></label><label>دقیقه<input type="number" name="minutes" value="60"></label><label>فعالیت<select name="activity"><option value="study">مطالعه</option><option value="test">تست</option><option value="review">مرور</option><option value="analysis">تحلیل</option><option value="summary">خلاصه</option></select></label><label>تمرکز<input type="number" min="1" max="5" name="focus_score" value="3"></label><label>یادداشت<textarea name="notes"></textarea></label></div><button class="btn">ثبت مطالعه</button></form><div class="card span-7"><h2>آخرین مطالعه‌ها</h2><div class="list">'; foreach($rows as $r) echo '<div class="item"><strong>'.h($r['subject_title']).' / '.h($r['topic_title']?:'-').'</strong><span class="small">'.h($r['studied_on']).'، '.h($r['minutes']).' دقیقه</span></div>'; echo '</div></div></section>'; }
if($view==='plan'){ $rows=all('SELECT * FROM plans ORDER BY due_on DESC,id DESC LIMIT 30'); echo '<div class="title"><h1>برنامه‌ریزی</h1></div><section class="grid"><form method="post" class="card span-5"><input type="hidden" name="action" value="plan"><div class="form-grid">'; st($subjects,$topics); echo '<label>تاریخ<input type="date" name="due_on" value="'.date('Y-m-d').'"></label><label>نوع<select name="scope"><option value="daily">روزانه</option><option value="weekly">هفتگی</option><option value="long">بلندمدت</option></select></label><label>عنوان<input name="title" required></label><label>هدف دقیقه<input type="number" name="target_minutes" value="60"></label></div><button class="btn">ثبت برنامه</button></form><div class="card span-7"><h2>برنامه‌ها</h2><div class="list">'; foreach($rows as $r) echo '<div class="item"><strong>'.h($r['title']).'</strong><span class="small">'.h($r['due_on']).' / '.h($r['status']).'</span><form method="post"><input type="hidden" name="action" value="done_plan"><input type="hidden" name="id" value="'.h($r['id']).'"><button class="btn secondary">انجام شد</button></form></div>'; echo '</div></div></section>'; }
if($view==='reviews'){ $rows=all("SELECT * FROM reviews WHERE status='due' ORDER BY due_on LIMIT 50"); echo '<div class="title"><h1>مرور فاصله‌دار</h1></div><div class="card"><div class="list">'; foreach($rows as $r) echo '<form method="post" class="item"><strong>'.h($r['item_type']).' #'.h($r['item_id']).'</strong><span class="small">سررسید: '.h($r['due_on']).'</span><input type="hidden" name="action" value="review"><input type="hidden" name="id" value="'.h($r['id']).'"><input type="hidden" name="item_type" value="'.h($r['item_type']).'"><input type="hidden" name="item_id" value="'.h($r['item_id']).'"><select name="recall_score"><option value="1">ضعیف</option><option value="3">متوسط</option><option value="5">عالی</option></select><button class="btn">ثبت مرور</button></form>'; if(!$rows) echo '<p class="small">مروری در صف نیست.</p>'; echo '</div></div>'; }
if($view==='pomodoro'){ echo '<div class="title"><h1>تایمر پومودورو</h1></div><section class="grid"><div class="card span-6 timer"><div><div class="time" data-timer>25:00</div><div class="actions"><input style="max-width:110px" name="pomodoro_minutes" type="number" value="25" onchange="setPomodoroMinutes(this.value)"><button class="btn" onclick="startTimer()">شروع</button><button class="btn secondary" onclick="pauseTimer()">مکث</button><button class="btn secondary" onclick="resetTimer()">ریست</button></div></div></div><form method="post" class="card span-6"><h2>ثبت پومودورو</h2><input type="hidden" name="action" value="pomodoro"><div class="form-grid">'; st($subjects,$topics); echo '<label>مدت<input type="number" name="minutes" value="25"></label></div><button class="btn">ثبت و تبدیل به مطالعه</button></form></section>'; }
if($view==='questions'){ $rows=all('SELECT questions.*,subjects.title subject_title FROM questions LEFT JOIN subjects ON subjects.id=questions.subject_id ORDER BY id DESC LIMIT 30'); echo '<div class="title"><h1>بانک سوال</h1></div><section class="grid"><form method="post" class="card span-6"><h2>ثبت سوال</h2><input type="hidden" name="action" value="question"><div class="form-grid">'; st($subjects,$topics); echo '<label>صورت سوال<textarea name="body" required></textarea></label><label>A<textarea name="option_a"></textarea></label><label>B<textarea name="option_b"></textarea></label><label>C<textarea name="option_c"></textarea></label><label>D<textarea name="option_d"></textarea></label><label>پاسخ<select name="correct_option"><option>A</option><option>B</option><option>C</option><option>D</option></select></label><label>منبع<input name="source"></label><label>سختی<select name="difficulty"><option value="easy">آسان</option><option value="medium">متوسط</option><option value="hard">سخت</option></select></label><label>نوع<select name="kind"><option value="conceptual">مفهومی</option><option value="memory">حفظی</option><option value="calculation">محاسباتی</option><option value="mixed">ترکیبی</option></select></label><label>توضیح<textarea name="explanation"></textarea></label></div><button class="btn">ذخیره</button></form><form method="post" class="card span-6"><h2>ورود گروهی</h2><input type="hidden" name="action" value="import_questions"><label>منبع<input name="source"></label><label>متن<textarea name="bulk_text"></textarea></label><button class="btn">ورود به بازبینی</button></form><div class="card span-12"><div class="list">'; foreach($rows as $r) echo '<div class="item"><strong>#'.h($r['id']).' '.h(mb_substr($r['body'],0,130)).'</strong><span class="small">'.h($r['subject_title']?:'بدون درس').' / '.h($r['status']).'</span></div>'; echo '</div></div></section>'; }
if($view==='exam'){ $tid=$_GET['topic_id']??''; $qs=$tid?all("SELECT * FROM questions WHERE topic_id=? AND status='approved' ORDER BY RAND() LIMIT 10",[$tid]):[]; echo '<div class="title"><h1>آزمون مبحثی</h1></div><section class="grid"><form method="get" class="card span-4"><input type="hidden" name="view" value="exam"><label>مبحث<select name="topic_id">'.opts($topics,$tid).'</select></label><button class="btn">ساخت آزمون</button></form>'; if($qs){ echo '<form method="post" class="card span-8"><input type="hidden" name="action" value="finish_exam"><input type="hidden" name="topic_id" value="'.h($tid).'">'; foreach($qs as $qu){ echo '<div class="item"><strong>'.h($qu['body']).'</strong><input type="hidden" name="question_ids[]" value="'.h($qu['id']).'">'; foreach(['A'=>'option_a','B'=>'option_b','C'=>'option_c','D'=>'option_d'] as $k=>$c) if($qu[$c]) echo '<label class="exam-option"><input type="radio" name="answer['.h($qu['id']).']" value="'.h($k).'"> '.h($k).') '.h($qu[$c]).'</label>'; echo '</div>'; } echo '<button class="btn">پایان و تحلیل</button></form>'; } echo '</section>'; }
if($view==='errors'){ $rows=all('SELECT * FROM error_logs ORDER BY occurred_on DESC,id DESC LIMIT 50'); echo '<div class="title"><h1>دفترچه خطاها</h1></div><section class="grid"><form method="post" class="card span-5"><input type="hidden" name="action" value="error"><div class="form-grid">'; st($subjects,$topics); echo '<label>تاریخ<input type="date" name="occurred_on" value="'.date('Y-m-d').'"></label><label>عنوان<input name="title" required></label><label>نوع<select name="error_type"><option value="conceptual">مفهومی</option><option value="memory">حفظی</option><option value="careless">بی‌دقتی</option><option value="time">زمان</option><option value="trap">دام تستی</option><option value="forgotten">فراموشی</option></select></label><label>وضعیت<select name="status"><option value="new">جدید</option><option value="review">نیازمند مرور</option><option value="fixed">اصلاح‌شده</option><option value="repeated">تکراری</option></select></label><label>شرح<textarea name="body"></textarea></label></div><button class="btn">ثبت خطا</button></form><div class="card span-7"><div class="list">'; foreach($rows as $r) echo '<div class="item"><strong>'.h($r['title']).'</strong><span class="small">'.h($r['error_type']).' / '.h($r['status']).'</span></div>'; echo '</div></div></section>'; }
if($view==='flashcards'){ $rows=all('SELECT * FROM flashcards ORDER BY id DESC LIMIT 40'); echo '<div class="title"><h1>فلش‌کارت</h1></div><section class="grid"><form method="post" class="card span-5"><input type="hidden" name="action" value="flashcard"><div class="form-grid">'; st($subjects,$topics); echo '<label>روی کارت<textarea name="front" required></textarea></label><label>پشت کارت<textarea name="back" required></textarea></label><label>سختی<select name="difficulty"><option value="easy">آسان</option><option value="medium">متوسط</option><option value="hard">سخت</option></select></label><label>مرور بعدی<input type="date" name="next_review_on" value="'.date('Y-m-d',strtotime('+1 day')).'"></label></div><button class="btn">ثبت کارت</button></form><form method="post" class="card span-7"><h2>ساخت با AI</h2><input type="hidden" name="action" value="ai_flashcards"><label>متن<textarea name="source_text"></textarea></label><button class="btn">ساخت پیش‌نویس</button>'; if(!empty($_SESSION['ai_result'])){ echo '<div class="item">'.nl2br(h($_SESSION['ai_result'])).'</div>'; unset($_SESSION['ai_result']); } echo '</form><div class="card span-12"><div class="list">'; foreach($rows as $r) echo '<div class="item"><strong>'.h($r['front']).'</strong><p>'.h($r['back']).'</p></div>'; echo '</div></div></section>'; }
if($view==='chat'){ $tid=$_GET['thread_id']??null; $threads=all('SELECT * FROM chat_threads ORDER BY id DESC LIMIT 20'); $msgs=$tid?all('SELECT * FROM chat_messages WHERE thread_id=? ORDER BY id',[$tid]):[]; echo '<div class="title"><h1>دستیار AI</h1></div><section class="grid"><div class="card span-4"><div class="list">'; foreach($threads as $t) echo '<a class="item" href="?view=chat&thread_id='.h($t['id']).'">'.h($t['title']).'</a>'; echo '</div></div><div class="card span-8"><div class="chat-box">'; foreach($msgs as $m) echo '<div class="msg '.h($m['role']).'">'.nl2br(h($m['body'])).'</div>'; echo '</div><form method="post"><input type="hidden" name="action" value="chat"><input type="hidden" name="thread_id" value="'.h($tid).'"><div class="form-grid">'; st($subjects,$topics); echo '<label style="grid-column:1/-1">پیام<textarea name="message" required></textarea></label></div><button class="btn">ارسال</button></form></div></section>'; }
if($view==='reports'){ $topicRows=all('SELECT topics.*,subjects.title subject_title FROM topics JOIN subjects ON subjects.id=topics.subject_id ORDER BY mastery ASC LIMIT 20'); $exams=all('SELECT * FROM exams ORDER BY taken_at DESC LIMIT 10'); echo '<div class="title"><h1>گزارش</h1></div><section class="grid"><div class="card span-6"><h2>مباحث پرریسک</h2><div class="list">'; foreach($topicRows as $t) echo '<div class="item"><strong>'.h($t['subject_title']).' / '.h($t['title']).'</strong><div class="progress"><i style="width:'.h($t['mastery']).'%"></i></div><span class="small">تسلط: '.h($t['mastery']).'%</span></div>'; echo '</div></div><div class="card span-6"><h2>آزمون‌ها</h2><div class="list">'; foreach($exams as $e) echo '<div class="item"><strong>'.h($e['title']).'</strong><span class="small">'.h($e['correct_answers']).' از '.h($e['total_questions']).'</span></div>'; echo '</div></div></section>'; }
echo '</main></div><script src="assets/app.js"></script></body></html>';
